### PR TITLE
Update cheatsheet with slight revisions

### PR DESCRIPTION
**Pull request by philipbelesky**
Hey, hope you've been well. I made a couple of revisions to the cheatsheet, mostly minor spacing tweaks, and a switch from using Illustrator to Affinity Designer. I think the most major change was using `oct` rather than `V` for the slider values ranges when working with quantisation. 

Let me know if/when any further updates are needed for the final MI firmware merge. I'd be happy to try and help with testing as well. I also [wrote a short blog post](https://philipbelesky.com/posts/stages-cheatsheet) about the module/manual that might be of interest.

### CODE REVIEW

**Comment by qiemem** [comment]
Great to hear from you Philip! Awesome work as usual!

For the final merge, I *think* that the only change will be that the ungated audio-rate LFOs now use the new band limited VCO code from Émilie, but have to go over everything to be sure. If you'd like to check it out, I've posted a test version here: https://github.com/qiemem/eurorack/issues/48.

Thanks again!

**Comment by philipbelesky** [comment]
That all sounds great! I've made a note to figure out those bits and update the manual when I have the time. Do let me know if you would prefer things are ready in a particular timeframe.

**Comment by ezzz01** [comment]
Great job, @philipbelesky !

One question though: the footer in the cheatsheet says "For firmware v1.2.0 by Bryan Head (Qiemem)", but where can I get that version?
The latest tag I see is https://github.com/qiemem/eurorack/tree/v1.1.0
And I saw this comment: https://github.com/qiemem/eurorack/issues/48#issuecomment-1426874557 , but that is for 1.2.2, isn't it?

**Comment by philipbelesky** [comment]
> Great job, @philipbelesky !
> 
> 
> 
> One question though: the footer in the cheatsheet says "For firmware v1.2.0 by Bryan Head (Qiemem)", but where can I get that version?
> 
> The latest tag I see is https://github.com/qiemem/eurorack/tree/v1.1.0
> 
> And I saw this comment: https://github.com/qiemem/eurorack/issues/48#issuecomment-1426874557 , but that is for 1.2.2, isn't it?

Hey, I think I was being more precise than I should be with that but of text. It probably should be understood as "v1.2.X" while things are still in beta and it can begin tracking specific versions just before or after a released is finalised.

**Pull request merged**
